AWSTemplateFormatVersion: 2010-09-09
Description: Template microservice using API Gateway and lambdas
Transform:
    - AWS::Serverless-2016-10-31

Parameters:
    DeploymentPrefix:
        Type: String
        Description: Prefix to be used in multiple places to differentiate different unique deployments
        Default: ''

Globals:
    Function:
        Layers:
            - !Ref RuntimeDependenciesLayer
        # Environment:
        #     Variables:
        #         ENV_VAR_NAME_1: 'value'
        Runtime: nodejs18.x
        MemorySize: 128
        Timeout: 100
    Api:
        # Auth:
        #     AddDefaultAuthorizerToCorsPreflight: false
        #     Authorizers:
        #         CustomAuthorizer:
        #             UserPoolArn: !Ref CognitoUserPoolArn
        #             AuthType: COGNITO_USER_POOLS
        #     DefaultAuthorizer: CustomAuthorizer
        Cors:
            AllowMethods: "'GET,POST,OPTIONS'"
            AllowHeaders: "'Content-Type,Authorization,Access-Control-Allow-Methods,Access-Control-Allow-Origin'"
            AllowOrigin: "'*'"

Resources:
    MsSampleAPIFunction:
        Type: AWS::Serverless::Function
        Metadata:
            BuildMethod: makefile
        Properties:
            FunctionName: !Sub 'ms-sample-api${DeploymentPrefix}'
            Handler: dist/handlers/sample-api.handler
            Description: Sample API handler lambda
            # Environment:
            #     Variables:
            #         ENV_VAR_NAME_2: 'value'
            # Policies:
            #     - DynamoDBCrudPolicy:
            #           TableName: !Ref SampleTable
            # - Statement:
            #       - Effect: Allow
            #         Resource: 'arn:aws:...'
            #         Action:
            #             - service:Action
            Events:
                Healthcheck:
                    Type: Api
                    Properties:
                        Path: /healthcheck
                        # Auth:
                        #     Authorizer: NONE
                        Method: get

    RuntimeDependenciesLayer:
        Type: AWS::Serverless::LayerVersion
        Metadata:
            BuildMethod: makefile
        Properties:
            LayerName: !Sub 'ms-sample-dependencies${DeploymentPrefix}'
            Description: Runtime dependencies for Lambdas
            ContentUri: ./
            RetentionPolicy: Retain

    # SampleTable:
    #     Type: AWS::DynamoDB::Table
    #     Properties:
    #         BillingMode: PAY_PER_REQUEST
    #         TableName: !Sub 'sample${DeploymentPrefix}'
    #         AttributeDefinitions:
    #             - AttributeName: id
    #               AttributeType: S
    #         KeySchema:
    #             - AttributeName: id
    #               KeyType: HASH

    APIDomainName:
        Type: AWS::ApiGateway::DomainName
        Properties:
            CertificateArn: arn:aws:acm:us-east-1:653284769887:certificate/a343fc90-7ad2-4761-8331-ddb604c99a1d
            DomainName: !Sub 'sample-api${DeploymentPrefix}.soffredi.org'

    APIBasePathMapping:
        Type: AWS::ApiGateway::BasePathMapping
        Properties:
            DomainName: !Ref APIDomainName
            RestApiId: !Ref ServerlessRestApi
            Stage: Prod

    APIDomain:
        Type: AWS::Route53::RecordSetGroup
        Properties:
            HostedZoneName: soffredi.org.
            RecordSets:
                - Name: !Sub 'sample-api${DeploymentPrefix}.soffredi.org'
                  Type: A
                  AliasTarget:
                      EvaluateTargetHealth: false
                      DNSName: !GetAtt APIDomainName.DistributionDomainName
                      HostedZoneId: !GetAtt APIDomainName.DistributionHostedZoneId

Outputs:
    SampleAPIBaseURL:
        Description: 'Sample API base URL'
        Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod'
